# Generated by Django 5.1.6 on 2025-03-05 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='Timestamp',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='Timestamp',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='auctions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
