# Generated by Django 5.1.6 on 2025-03-15 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='category',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='auction_category', to='auctions.categories'),
        ),
    ]
