# Generated by Django 5.1.6 on 2025-03-05 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_timestamp_bids_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='price',
            field=models.IntegerField(),
        ),
    ]
