# Generated by Django 5.1.6 on 2025-03-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctions_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='image',
            field=models.CharField(max_length=250),
        ),
    ]
