# Generated by Django 5.1.6 on 2025-03-06 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_wishlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishlist',
            new_name='Watchlist',
        ),
    ]
