# Generated by Django 5.1.6 on 2025-03-13 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_wishlist_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='status',
            field=models.CharField(default='open', max_length=10),
            preserve_default=False,
        ),
    ]
